### ISSUE TITLE
Fix consul-exporter so that it supports arm64.

### ISSUE THREAD

**Issue by RedstoneWizard08** [GitPod-Arm/bitnami-compat#1]
```
         # TODO: Fix consul-exporter so that it supports arm64.
```

https://github.com/GitPod-Arm/bitnami-compat/blob/3df98ac5199f2459023235535a800885dca245df/.github/workflows/build-on-push.yml#L70
https://github.com/GitPod-Arm/bitnami-compat/runs/4983388850?check_suite_focus=true#step:11:1180

**Comment by RedstoneWizard08** [comment]
Looks like the code is here
https://github.com/prometheus/consul_exporter

**Comment by ZCube** [comment]
> Looks like the code is here https://github.com/prometheus/consul_exporter

Try this way!

1.  Clone bitnami-compat

2.  Clone https://github.com/bitnami/bitnami-docker-consul-exporter in bitnami-compat

3. ./scripts/create.sh

4. There are 2 method to brind binaries here.

4.1 docker/consul-exporter/0.7.1-4 use docker/consul/1.11.2-2 as template.

or 

4.2  golang/consul-exporter/0.7.1-4 use golang/ini-file/1.4.1-3 as template.

5. You need to check bitnami's binary. by download
```
export name="consul-exporter"
export version="0.7.1-4"
export OS_NAME=linux
export OS_ARCH=amd64
export OS_FLAVOUR=debian-10
export base_name="${name}-${version}-${OS_NAME}-${OS_ARCH}-${OS_FLAVOUR}"
export DOWNLOAD_URL="https://downloads.bitnami.com/files/stacksmith"
curl -LO "${DOWNLOAD_URL}/${base_name}.tar.gz"
```

6. And use your time !

**Comment by ZCube** [comment]
Select https://hub.docker.com/r/prom/consul-exporter or https://github.com/prometheus/consul_exporter

I prefer https://hub.docker.com/r/prom/consul-exporter.
Golang-based binaries do not require rebuilding.

**Comment by RedstoneWizard08** [comment]
```
gitpod /workspace/bitnami-compat/consul-exporter-0.7.1-4-linux-amd64-debian-10/files/consul-exporter/bin $ file consul_exporter 
consul_exporter: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=9yiKikEar5s_xkOYpbAi/6jw1ibv1xdG9bRa-MFVW/gXu7Zh_YD60py50-iQjt/_3GQrx-uZaxNguRJY86S, not stripped
gitpod /workspace/bitnami-compat/consul-exporter-0.7.1-4-linux-amd64-debian-10/files/consul-exporter/bin $ 
```

**Comment by ZCube** [comment]
@RedstoneWizard08 Wow.... I thought bitnami would manage all binaries like this.....
```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "ini-file" "1.4.1-3" --checksum 26f2ba99a02266d6f3857a3a11db7ed441d76a2fbc1066a17d4b0b17b047e01d
```

**Comment by RedstoneWizard08** [comment]
[consul-exporter-0.7.1-4-linux-amd64-debian-10.tar.gz](https://github.com/GitPod-Arm/bitnami-compat/files/7960470/consul-exporter-0.7.1-4-linux-amd64-debian-10.tar.gz)
[consul-exporter-0.7.1-4-linux-arm64-debian-10.tar.gz](https://github.com/GitPod-Arm/bitnami-compat/files/7960473/consul-exporter-0.7.1-4-linux-arm64-debian-10.tar.gz)

**Comment by ZCube** [comment]
Even if you look at the Dockerfile, consul-exporter is directly executed without a separate script, and there is no script for environment variables.

```
ENTRYPOINT [ "consul_exporter" ]
```

So, in the case of this image, it is recommended to use prom/consul-exporter.

**Comment by ZCube** [comment]
```
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: prom/consul-exporter
    tag: v0.7.1
    pullPolicy: IfNotPresent
```

**Comment by RedstoneWizard08** [comment]
Oh. I thought I had to use the bitnami image.

**Comment by RedstoneWizard08** [comment]
Well, thanks!
